# Copyright 2025-2026 Strands RL Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The per-sample input type for `Tau2BenchEnv`."""

from __future__ import annotations

from functools import cached_property
from typing import TYPE_CHECKING, Any, Literal

from pydantic import Field
from strands.types.content import Message

from strands_env.core import Task

from . import _tau2

if TYPE_CHECKING:
    from ._tau2 import Tau2Environment, Tau2Task


class Tau2BenchTask(Task):
    """One tau2 task: its domain plus the serialized tau2 `Task`."""

    message: str | Message = Field(
        default="", description="Task message generated by the user simulator at rollout time."
    )
    domain: Literal["airline", "retail", "telecom"] = Field(description="Tau2 domain.")
    config: dict[str, Any] = Field(description="Tau2 task serialized to a dict.")

    @cached_property
    def tau2_task(self) -> Tau2Task:
        """Parsed tau2 task."""
        return _tau2.Tau2Task.model_validate(self.config)

    @cached_property
    def tau2_env(self) -> Tau2Environment:
        """Built tau2 environment (the live world; cached, so the episode and the reward see the same instance)."""
        return _tau2.build_task_environment(self.domain, self.tau2_task)
