"""The per-sample input type for `Tau2BenchEnv`."""

from __future__ import annotations

from functools import cached_property
from typing import TYPE_CHECKING, Any, Literal

from pydantic import Field
from strands.types.content import Message

from strands_env.core import Task

from . import _tau2

if TYPE_CHECKING:
    from ._tau2 import Tau2Environment, Tau2Task


class Tau2BenchTask(Task):
    """One tau2 task: its domain plus the serialized tau2 `Task`."""

    message: str | Message = Field(
        default="", description="Task message generated by the user simulator at rollout time."
    )
    domain: Literal["airline", "retail", "telecom"] = Field(description="Tau2 domain.")
    config: dict[str, Any] = Field(description="Tau2 task serialized to a dict.")

    @cached_property
    def tau2_task(self) -> Tau2Task:
        """Parsed tau2 task."""
        return _tau2.Tau2Task.model_validate(self.config)

    @cached_property
    def tau2_env(self) -> Tau2Environment:
        """Built tau2 environment (the live world; cached, so the episode and the reward see the same instance)."""
        return _tau2.build_task_environment(self.domain, self.tau2_task)
